version: "3.7"
services:
  kplserver:
    image: quay.io/turner/kplserver
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      AWS_DEFAULT_REGION: us-east-1
      AWS_PROFILE: ${AWS_PROFILE}
      KINESIS_STREAM: ${KINESIS_STREAM}
      DLQ_URL: ${DLQ_URL}
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
